# Project information
site_name: My MkDocs Project
site_description: 'An example MkDocs project using the Material theme'
site_url: 'https://benie-joy-possi.github.io/mk-docs'  # Change this to my site's URL

# Theme settings
theme:
  name: material


# Navbar settings (site structure)
nav:
  - Home: index.md
  - About: about.md
  - Multipass: multipass.md

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository configuration (for the edit link on pages)
repo_name: benie-joy-possi/mk-docs
repo_url: https://github.com/benie-joy-possi/mk-docs
edit_uri: edit/master/docs/
